AllCops:
  Exclude:
    - bin/*
    - config/application.rb
    - config/initializers/*
    - db/migrate/*
    - db/schema.rb
    - spec/spec_helper.rb
Documentation:
  Enabled: false

LineLength:
  Max: 120